### ISSUE TITLE
Does P4Utils Support IPv6 ？

### ISSUE THREAD

**Issue by liudsl** [nsg-ethz/p4-utils#66]
Hi everyone:
 
I want to do something about SRv6, specifically using BMV2 to implement SRv6,  but I found that the function `net.setIntfIp()`  cannot set the IPv6 address for host. How should I solve it?

Thank you very much!

here is my code:

```python
#! /usr/bin/python3


net = NetworkAPI()

# Network general options
net.setLogLevel('info')
net.enableCli()

# Network definition
net.addSwitch("s1")
net.addHost('h1')
net.addHost('h2')

net.addLink('h1', 's1', port2=1)
net.addLink('s1', 'h2', port1=2)

net.setIntfIp("h1", "s1", "2001:db00::0/24")
# Assignment strategy
# net.l2()

# Nodes general options
net.enableLogAll()

# Start the network
net.startNetwork()
```

And Here is the output after `sudo python3 network`:

```shell
.......
Topology saved to disk!
Programming switches...
Switches programmed correctly!
Programming hosts...

Traceback (most recent call last):
  File "network.py", line 39, in <module>
    net.startNetwork()
  File "/home/ubuntu/p4-tools/p4-utils/p4utils/mininetlib/network_API.py", line 1135, in startNetwork
    self.program_hosts()
  File "/home/ubuntu/p4-tools/p4-utils/p4utils/mininetlib/network_API.py", line 341, in program_hosts
    '{}/{}'.format(intf1.ip, intf1.prefixLen))
  File "/usr/lib/python3.6/ipaddress.py", line 119, in ip_interface
    address)
ValueError: 'None/24' does not appear to be an IPv4 or IPv6 interface
```

**Comment by huyongqingandczw** [comment]
I have some questions about registers. Do you have time? May I have your email address

**Comment by edgar-costa** [comment]
@liudsl Unfortunately, for most features we do not have support for IPv6. 

To solve it you would need to adapt the code in all the placers where we assume addresses are IPv4.

**Comment by huyongqingandczw** [comment]
> @liudsl Unfortunately, for most features we do not have support for IPv6.
> 
> To solve it you would need to adapt the code in all the placers where we assume addresses are IPv4.

n my P4 program, I am storing the source IP address and destination IP address of data packets in registers. However, when I attempt to read these values from the controller(register_read()), I receive a sequence of numerical values instead of the expected IP addresses. Also, I write the network five-tuple(srcIP,dstIP,proto,srcPort,dstPort) to a register, but the value read at the corresponding index position is -1.
I would greatly appreciate your assistance in understanding why this discrepancy is occurring. Specifically, I would like to know:
1. Is there a specific format or encoding used when storing IP addresses in  registers?
2. How should I interpret the numerical values obtained from the controller to retrieve the original IP addresses?
3. Are there any additional steps or considerations I need to take into account when working with IP addresses in  registers?
4.How do you write a five-tuple perfectly in a register

**Comment by edgar-costa** [comment]
@huyongqingandczw Why do you write your question in this git issue thread, I don't think what you are asking has anything to do with the original question. Can you please not do that? 

If your question is unrelated to the current thread, I kindly suggest creating a new issue or finding a thread that aligns more closely with your topic.

**Comment by jose-galvao** [comment]
Hello @liudsl what did you do to solve that?
