### ISSUE TITLE
p4run problem

### ISSUE THREAD

**Issue by zwllwz823** [nsg-ethz/p4-utils#68]
Hey everyone,
I just used copy my p4app.json to the p4run folder and use these commands:
p4run
sudo p4run
sudo p4run --config p4app.json
But all of these commands gives me the feedback:

Traceback (most recent call last):
  File "/usr/local/bin/p4run", line 11, in <module>
    load_entry_point('p4utils', 'console_scripts', 'p4run')()
  File "/home/zwl/p4-utils/p4utils/p4run.py", line 736, in main
    app = AppRunner(args.config,
  File "/home/zwl/p4-utils/p4utils/p4run.py", line 308, in __init__
    mininet = load_custom_object(mininet_module)
  File "/home/zwl/p4-utils/p4utils/utils/helper.py", line 321, in load_custom_object
    module = importlib.import_module(module_name)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'p4utils.mininetlib.p4net'

I tried many ways but no one works. 
I even uninstall p4utils and install again in my VM but it still goes wrong.
can anyone help me please...

**Comment by edgar-costa** [comment]
I believe its a problem with your installation and python installation. 

Can you try `import p4utils` with python3?

**Comment by a5539322** [comment]
@edgar-costa hello I also encountered this problem, can you explain it in detail? I am a student, thank you very much

**Comment by a5539322** [comment]
Replenish:I installed it using the "install-p4-dev.sh" provided on this website. This picture is the situation I encountered. It is the same as this problem. I will encounter this problem when using all the sample programs on the Internet. , except the "examples" provided by p4utils itself can be executed, others cannot. Please help me solve this problem. I really need to use this to complete my studies. Thank you.
![messageImage_1702932855316](https://github.com/nsg-ethz/p4-utils/assets/121971285/927088cd-1890-41bf-911f-67157d4d6dde)

**Comment by edgar-costa** [comment]
@a5539322 the problem you are showing in the screenshot has nothing to do with the thread. 

Open a new issue. But in any case the problem is due to your code using the old version of p4-utils, p4net does not exist anymore. You will have to look at the new examples, there is plenty here: https://github.com/nsg-ethz/p4-learning/tree/master and translate your code so the imports work.

**Comment by a5539322** [comment]
@edgar-costa Thank you very much for your help. Now I understand the situation I encountered. I will try to solve this problem again. Since I am only a student, I may have a poor understanding of many things. If I really can't solve it, I will ask again. Really Thank you very much for your help
